name: Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Run tests
        run: php tests/run.php
